name: Deploy Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create plugin archive
      run: |
        mkdir -p dist
        zip -r dist/lgwd-ai-chatbot.zip . -x ".*" "dist/*" "node_modules/*" "*.md" "package*.json"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./dist/lgwd-ai-chatbot.zip
        body: |
          ## LGWD AI Chatbot Release ${{ github.ref_name }}
          
          Professional WordPress AI Chatbot with n8n Chat Trigger Integration
          
          ### What's New:
          - Enhanced mobile responsiveness
          - Improved n8n Chat Trigger integration
          - Professional admin interface
          - Full WordPress standards compliance
          
          ### Installation:
          1. Download lgwd-ai-chatbot.zip
          2. Upload to WordPress Admin → Plugins → Add New → Upload Plugin
          3. Activate and configure with your n8n Chat Trigger URL
          
          **Professional Setup Available:** [lionsgatewebdesign.com](https://lionsgatewebdesign.com)
